### ISSUE TITLE
[core] fix release build failed

### ISSUE THREAD

**Issue by one-thunder** [ThunderstormPro/l2next-crypto#57]
It's failing due to how yaml is setting debug compile flags. 

Need to investigate and fix that, but it's not urgent.

**Comment by one-lightning** [comment]
This issue should be fixed asap

![MSVCP140D](https://user-images.githubusercontent.com/49819514/66718431-989cfa00-edec-11e9-94ef-52ee67639b40.jpg)
![UCRTBASED](https://user-images.githubusercontent.com/49819514/66718432-99359080-edec-11e9-946f-f0eafc8623e7.jpg)
![VCRUNTIME140_1D](https://user-images.githubusercontent.com/49819514/66718433-99359080-edec-11e9-82df-e6a0fd8bad2a.jpg)
![VCRUNTIME140D](https://user-images.githubusercontent.com/49819514/66718434-99359080-edec-11e9-8b16-cd9a0dbac63a.jpg)
